name: cd

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build:

    strategy:
      matrix:
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Wait for CI workflow to succeed
        uses: ArcticLampyrid/action-wait-for-workflow@v1.0.4
        with:
          workflow: ci.yml
          sha: ${{ github.sha }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: recoll-api-rest:latest
